import { Box, Button, Typography } from '@mui/material'
import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/header/header'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <Box
          display={"flex"}
          flexDirection="column"
          justifyContent="center"
          alignItems={"center"}
          sx={{ backgroundImage: 'url(/banner.jpg)', backgroundPosition: 'center', backgroundSize: 'cover' }}
          height={"calc(100vh)"}
        >
          <Box
            sx={{ background: "rgba(0, 0, 0, 0.2)", px: 4, py: 3, borderRadius: 3 }}
            display={"flex"}
            flexDirection="column"
            justifyContent="center"
            alignItems={"center"}
            maxWidth={1000}
          >
            <Typography
              variant='h2'
              textAlign={"center"}
              mb={4}
              fontWeight={600}
              color="#FFF"
              textTransform={"uppercase"}
              sx={{ fontSize: { xs: 24, md: 48 } }}
            >
              Highest Quality Care
            </Typography>
            <Typography
              mb={4}
              color="#FFF"
              textAlign={"center"}
            >
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus id dignissim justo. Nulla ut facilisis ligula. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed malesuada lobortis pretium.
            </Typography>
            <Button variant='contained' size='large' color="error">
              Discover Now
            </Button>
          </Box>
        </Box>
      </main>
    </>
  )
}

export default Home
