import { Box } from "@mui/material";
import Head from "next/head";
import LoginComponent from "../components/login/login";

function LoginPage() {
    return (
        <>
            <Head>
                <title>Login</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Box
                    display={"flex"}
                    justifyContent="center"
                    alignItems={"center"}
                    height={"100vh"}
                    sx={{ backgroundColor: "rgb(227, 242, 253)" }}
                >
                    <LoginComponent />
                </Box>
            </main>
        </>
    );
}

export default LoginPage;