import { Avatar, Box, Button, Container, Divider, Grid, Stack, Typography } from "@mui/material";
import Head from "next/head";
import Header, { useUser } from "../components/header/header";
import ExamItem from "../components/items/form-item";
import ReplayIcon from '@mui/icons-material/Replay';

import { useAuth } from "../hooks/auth.hook";
import { useEffect } from "react";
import { useRouter } from "next/router";
import LoadingScreen from "../components/loading/loading";
import useSWR from "swr";
import { API_URL } from "../constants/api";
import { fetcher } from "../utils/swr";
import { ContestInterface } from "../types/contest";
import FormItem from "../components/items/form-item";

function MainPage() {

    const router = useRouter()
    const { accessToken, loading } = useAuth()
    const { user, isLoading, isError } = useUser(accessToken)

    const { data } = useSWR<ContestInterface[]>(accessToken ? [API_URL + `/contest/get`, accessToken] : null, fetcher)

    useEffect(() => {
        if((!user && isError) || (!loading && !accessToken)) {
            router.push("/login")
        }
    }, [user, isError])


    // JSX renderer

    const renderContests = () => {
        let result;
        
        if(data) {    
            result = data.map((contest, index) => {
                return <FormItem form={contest.form} key={index} contestCode={contest.code}/>
            })
        }

        return result;
    }

    if(!user || isLoading) {
        return <LoadingScreen />
    }

    return (
        <>
            <Head>
                <title>Main Page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main style={{ backgroundColor: "#eee", minHeight: '100vh' }}>
                <Container sx={{ paddingTop: 12, backgroundColor: "#fff", minHeight: '100vh' }}>
                    <Grid container spacing={2}>
                        <Grid xs={12} md={4} item>
                            <Box borderRight="1px solid #eee" height={'100%'}>
                                <Box display={"flex"} justifyContent="space-between" alignItems={"flex-end"}>
                                    <Typography fontSize={20} fontWeight={500} textTransform="uppercase">
                                        Tài khoản của bạn
                                    </Typography>
                                </Box>
                                <Typography color="#777" mt={1}>
                                    Thông tin cá nhân
                                </Typography>
                                <Divider sx={{ my: 1 }} />
                                <Box display={"flex"} mt={2}>
                                    <Avatar alt="" sx={{ width: 100, height: 100 }} src="/icons/man.png" />
                                    <Box ml={2}>
                                        <Typography fontSize={18} fontWeight={600} mb={0.5}>{user.name}</Typography>
                                        <Typography fontSize={14} color="#777">Email: {user.email}</Typography>
                                        <Typography fontSize={14} color="#777">Phone: {user.phone}</Typography>
                                        <Typography fontSize={14} color="#777">Address: {user.address}</Typography>
                                    </Box>
                                </Box>
                            </Box>
                        </Grid>
                        <Grid xs={12} md={8} item>
                            <Box display={"flex"} justifyContent="space-between" alignItems={"flex-end"}>
                                <Typography fontSize={20} fontWeight={500} textTransform="uppercase">
                                    Danh sách bảng câu hỏi
                                </Typography>
                                <Button variant="outlined" startIcon={<ReplayIcon />} size="small">
                                    Reload
                                </Button>
                            </Box>
                            <Typography color="#777" mt={1}>
                                Chọn một và bắt đầu tiến hành ngay !
                            </Typography>
                            <Divider sx={{ my: 1 }} />
                            <Stack direction="column" spacing={2}>
                                {renderContests()}
                            </Stack>
                        </Grid>
                    </Grid>
                </Container>
            </main>
        </>
    );
}

export default MainPage;